// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvCAcDzUVJal4aDUOUFBdjsncaeMArn9I',
    appId: '1:450691197443:web:a41e781d9c94e2c02afc36',
    messagingSenderId: '450691197443',
    projectId: 'diem-5a68c',
    authDomain: 'diem-5a68c.firebaseapp.com',
    storageBucket: 'diem-5a68c.appspot.com',
    measurementId: 'G-YLBZ5G4WNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVXhgz78yu5kQwAmrWLGgHEMmkoBTzlGo',
    appId: '1:450691197443:android:6970f052c6e0e0f02afc36',
    messagingSenderId: '450691197443',
    projectId: 'diem-5a68c',
    storageBucket: 'diem-5a68c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFqRrjx-rVGBzUc6OWGtYZX0O0RBEEPaA',
    appId: '1:450691197443:ios:a5664839755fd29f2afc36',
    messagingSenderId: '450691197443',
    projectId: 'diem-5a68c',
    storageBucket: 'diem-5a68c.appspot.com',
    iosClientId: '450691197443-63uouu2g078g8qh4e3mjk6i5p0ke0co6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailylog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFqRrjx-rVGBzUc6OWGtYZX0O0RBEEPaA',
    appId: '1:450691197443:ios:a5664839755fd29f2afc36',
    messagingSenderId: '450691197443',
    projectId: 'diem-5a68c',
    storageBucket: 'diem-5a68c.appspot.com',
    iosClientId: '450691197443-63uouu2g078g8qh4e3mjk6i5p0ke0co6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dailylog',
  );
}
